#!/bin/sh

# This is the absolute path to the repo.
ABSPATH="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"

# use the prepend function
. "$ABSPATH/.bash_subshell"

# Handle: given a file as a first argument,
# include it in a file given as a second arg
# if it is not already there.
handle () {
	# check whether we need to locate the true path or use literal $ABSPATH
	if [ -f "$ABSPATH/$1" ]; then
		local new_text="\"$ABSPATH/$1\""
	else
		local new_text="$1"
	fi
	local new_text="test -f $new_text && . $new_text"
	if [ -z "$(grep -Fsx "$new_text" "$2")" ]; then
		echo "Including $1."
		prepend "$2" "$new_text"
	fi
}

# If there are no arguments, then include all.
if [ $# -eq 0 ]; then
	FILES="$(cd "$ABSPATH" && echo .bash_*)"
else
	FILES="$(echo " $@" | sed 's/ / .bash_/g')"
fi

for f in "$FILES"; do
	handle "$f" "$ABSPATH/.included"
done

# Set up global var for the path to this directory.
# Use grep to retrieve the contents of .included without the ABSPATH declaration
echo "$(echo "ABSPATH='$ABSPATH'"; grep -svx "ABSPATH=.*" "$ABSPATH/.included")" > "$ABSPATH/.included"

# If .bash_aliases doesn't already include .included, make it do that.
handle "$ABSPATH/.included" "$HOME"/.bash_aliases
